version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:8080
    links:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongo:27017/movierental"

    depends_on:
      - mongo
  mongo:
    image: mongo